apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: 728156710202.dkr.ecr.ap-northeast-2.amazonaws.com/app-back:v114
        name: app-back
        command: ["/bin/sh", "-c", "sleep 5 && python manage.py makemigrations && python manage.py migrate && gunicorn dr_tart.wsgi --bind 0.0.0.0:8000"]
        envFrom:
          - configMapRef:
              name: app-back-cm
        ports:
        - containerPort: 8000
