apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: 728156710202.dkr.ecr.ap-northeast-2.amazonaws.com/app-front:v42
        name: app-front
        envFrom:
        - configMapRef:
            name: front-cm
        ports:
        - containerPort: 80
